# Generated by Django 3.2.5 on 2021-09-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_porduct_date'),
        ('data_tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='product',
            field=models.ManyToManyField(blank=True, to='products.Porduct'),
        ),
    ]
