# Generated by Django 3.2.5 on 2021-08-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='porduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='Porduct_image/%Y/%m/%d/'),
        ),
    ]
