# Generated by Django 3.2.5 on 2021-09-17 13:55

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_porduct_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='porduct',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='porduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path),
        ),
    ]
