# Generated by Django 3.2.5 on 2021-09-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210917_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='porduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
