# Generated by Django 3.2.5 on 2021-09-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_porduct_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porduct',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
