# Generated by Django 3.2.5 on 2021-09-23 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_porduct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='porduct',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
